services:
  db:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  python-app:
    build: ./python
    container_name: python_app
    restart: on-failure
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_INTERNAL_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./python:/app
    depends_on:
      db:
        condition: service_healthy

  go-app:
    build: ./golang
    container_name: go_app
    restart: on-failure
    env_file:
      - ./golang/.env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_INTERNAL_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./golang:/app

    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: